services:
  pgstac:
    container_name: pgstac
    image: pgstac
    build:
      context: .
      network: host
      dockerfile: docker/pgstac/Dockerfile
      target: pgstac
    platform: windows/amd64
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgis
      - PGUSER=postgis
      - PGPASSWORD=postgis
      - PGDATABASE=postgis
    ports:
      - "5439:5432"
    volumes:
      - pgstac-pgdata:/var/lib/postgresql/data
    command: postgres
volumes:
  pgstac-pgdata:
